language: python
python:
    - "2.7"
    - "3.5"
install:
    - pip install -r requirements.txt
    - pip install -r requirements_test.txt
script: nosetests --with-coverage --cover-package=flask_permissions
