language: python
python:
  - 3.7.6
services: 
  - docker
install: 
  - docker build -t yuxio/ffp .
  - docker run -d --name=ffp -p 127.0.0.1:502:80 --restart=always yuxio/ffp:latest
before_script:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install coverage
  - pip install coveralls
script:
  - docker ps | grep -q yuxio/ffp
  - pytest
  - coverage run --source=. -m unittest discover
after_success:
  - coveralls
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push yuxio/ffp