model: chatbot.DynamicBot
dataset: data.Ubuntu
model_params:
  base_cell: GRUCell
  ckpt_dir: out/ubuntu/basic
  decode: False
  batch_size: 128
  decoder.class: BasicDecoder
  encoder.class: BasicEncoder
  embed_size: 128
  learning_rate: 0.002
  num_layers: 1
  reset_model: True
  state_size: 512
  steps_per_ckpt: 100
dataset_params:
  data_dir: /home/brandon/Datasets/ubuntu
  vocab_size: 60000
  max_seq_len: 12
  optimize_params: true
