---

- name: Create code directory
  file:
    path: "{{ project_directory }}"
    owner: "{{ gunicorn_user }}"
    group: "{{ gunicorn_group }}"
    state: directory
    mode: 0755

- name: Copy the code from repository
  git:
    repo: "{{ repository }}"
    dest: "{{ project_directory }}"
    force: yes
    accept_hostkey: yes
  become_user: "{{ gunicorn_user }}"

- name: Ensure the application log folder exists
  file:
    path: "{{ application_log_dir }}"
    mode: 0774
    state: directory

- name: Ensure the application log file exists
  copy:
    content: ""
    dest: "{{ gunicorn_log_file }}"
    mode: 0664
    force: no

- name: Ensure that the application file permissions are set properly
  file:
    path: "{{ project_directory }}"
    owner: "{{ gunicorn_user }}"
    group: "{{ gunicorn_group }}"
    recurse: yes
