---

- name: Ensure the Supervisor service is running
  service: name=supervisor state=started enabled=yes

- name: Create the Supervisor config file
  template:
    src: supervisor.conf.j2
    dest: /etc/supervisor/conf.d/{{ project_name }}.conf
    backup: yes
  become: yes

- name: Re-read the Supervisor config files
  supervisorctl: name={{ project_name }} state=restarted
  become: yes
