trigger:
  branches:
    include: [master, test-me-*]
  tags:
    include: ['*']

resources:
  repositories:
    - repository: sloria
      type: github
      endpoint: github
      name: sloria/azure-pipeline-templates
      ref: refs/heads/sloria

stages:
  - stage: lint
    jobs:
      - template: job--python-tox.yml@sloria
        parameters:
          toxenvs: [lint]
          coverage: false
  - stage: test
    jobs:
      - template: job--python-tox.yml@sloria
        parameters:
          toxenvs: [py36, py39]
          coverage: true
  - stage: release
    jobs:
      - template: job--pypi-release.yml@sloria
