language: python
script: true
deploy:
  provider: pypi
  user: __token__
  password:
    secure: tUByiJKJv7Eh23U5X/Gh+5V0+zJ5blonft2N2ccldVJYIdf/cAsoY1a/agJsiIeO8Qoqik9XdrwoZUQqV+F4/SHFGJLVC9fXRriLSE2m78jIu+Qxxn9KSnJPXr5JOsBFyAmZ71Sma5yuL8D6VQpPEwucgs1HhqyrL2PUNnW/OHOHBH6FXMK/uGKdQj+6lniJANJxY/LbwhgifqOnuB/EZl3zF0dkBH/APsH+spPEC1G66bxkTjEqp0nX4DuaSdjs9y972ndrlPJ6HUxQCeX5KX2+PbZNZgkhUhlTwFJ+/j1ky38oE1V4GjloPnRZBmg9IkzPsjiQqL/P7mqCc10ZJxm6kmPuK04SEMK6iB0m45pxZX2PkfbOhI/E9rbqC6QXS00rdSLlUVFJHPcf55HXHXGNnOwmYENIfmKtfkvAmGeTCTh+71rute84UwrkmfYQZln7Ak3+cav1XgawkZme0itjIu5BqnE7Ypnu56hfzJ/eRMTpKyIJiKcBs8EkO7ft/E5LwQC54akN874hyy8odeWv7El/j7RVL1/7JcQrSlgVrb7xQgBIVH09FhDwIluQv6iHWKq5Gz5X0O+BFDDmxrQisyn60mDNGc8fziiezFMrijT3htE8SveVryCRCYY8IOhuL1nfy/2Fqu1Iheb3nHdmSPdDrQ6mBGDfXgYt8r0=
  distributions: sdist bdist_wheel
  skip_existing: true
  before_deploy: echo 'ready?'
  deploy: echo 'during deploy'
  after_deploy: echo 'post deploy'
