language: python
cache: pip

python:
  - "2.7"
  #- "3.3"
  #- "3.4"
  #- "3.5"
  #- "3.6"
  #- "3.7"
  
install:
  - pip install .
  - pip install -r requirements-dev.txt

script:
  # TODO: uncomment isort and flake8 when it will start passing
  # - isort --check-only
  # - flake8 --max-line-length=120
  - pytest
