name: Linting Tests
# Only for last versions of python

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "linting"
            python: "3.8"
            tox_env: "lint"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox virtualenv
    - name: Test build
      run: "tox -e ${{ matrix.tox_env }}"
