exclude: 'docs'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: requirements-txt-fixer

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.1
    hooks:
      - id: flake8
        language_version: python3
        args: ['src/slackify', 'tests', 'examples']
