name: Deploy backend files

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'static/**'
      - 'nginx/**'
      - README.md
      - LICENSE

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to Server
      uses: AEnterprise/rsync-deploy@v1.0
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        ARGS: -avz --delete --exclude='*.pyc'
        SERVER_PORT: '22'
        FOLDER: pyproject.toml pdm.lock ./docker-compose.yml Dockerfile flaskblog migrations start_server.sh
        SERVER_IP: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USERNAME }}
        SERVER_DESTINATION: /home/fming/frostming.com/
    - name: Rebuild and Restart Docker
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd /home/fming/frostming.com
          sudo docker-compose build web
          docker-compose up -d --force-recreate --no-deps web
