language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- pypy
install:
- pip install -r requirements.txt
- python setup.py develop
script:
- python setup.py test
- cd docs && make html
env:
  global:
  - secure: QktJb8B+STvIhcKu4oCG2f0W5IqzHkQVPP4uE5nxCZw64tKTRGhiHmtofxRMDqKl6ORlc9dSn8yHpyR4kCwDXSGYiOJi3jnI2bKz7DoqiKry5y+/PaUvJhYuVKfirTr2F5Wwzi1c06Zm7jQ1EpRqMe8qiZaqw1G5JGRDwnpqzoA=
  - secure: V5HoVHPokoTRfpZstIn/O542w4dStXnAUwxSMTl1EzyaBMqONvBiW28Xkbxh5XekLa3NumoZKh9ZZQ7WwNXO00pmieNeYLXcWByztF937ozsraBHhmTnVvK59O4IkxlVy/jlxHrtIcRMdzXuIyubOppzYVUSc/rP+sbXXI4314Y=
