tasks:
 - tox -e flake8
 - tox -e isort
 - tox -e pillow
 - tox -e django18
 - tox -e django19
 - tox -e redis
 - tox -e coverage-report
 - tox -e docs

services:
 - redis-server

coverage:
  path: coverage.xml
  parser: python
