---
- name: Install Nginx, Postgres and application
  hosts: all
  roles:
    - { role: common, become: yes }
    - { role: mongo, become: yes }
    - { role: web, become: yes }
    - { role: nginx, become: yes }
