sudo:
  - required

language:
  - python

services:
  - postgresql

python:
  - 3.5

install:
  - pip install -r core/requirements.txt

before_script:
  - chown -R 1000:1000 .
  - find . -name .cache -prune -exec rm -rf {} +
  - psql -c 'CREATE DATABASE "flusk-test";' -U postgres

script: pytest -s
