language: python
install:
    - pip install flask

python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "pypy"

script:
    - python setup.py -q nosetests

after_success:
    - pip install coveralls
    - coverage run --source=flask_weixin setup.py -q nosetests
    - coveralls

notifications:
    email: false
