language: python
sudo: required
dist: xenial

addons:
  apt:
    packages:
    - git
    - mosquitto

python:
  - "3.6"
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  - pip install -e .
  - pip install coverage coveralls pytest-cov mypy

script:
  bash deploy.sh

after_success:
  coveralls
