version: '2'

services:
  redis:
    restart: always
    image: redis

  #mariadb:
  #  restart: always
  #  image: mariadb
  #  environment:
  #    - MYSQL_USER=burpui
  #    - MYSQL_PASSWORD=burpui
  #    - MYSQL_DATABASE=burpuidb
  #    - MYSQL_RANDOM_ROOT_PASSWORD=yes
  #    - TZ=Europe/Paris
  ## Additionally, you may want to persist data
  ## volumes:
  ##   - /var/lib/buistore/mariadb:/var/lib/mysql

  pgsql:
    restart: always
    image: registry.ziirish.me/ziirish/burp-ui/pgsql:10
    environment:
      - POSTGRES_PASSWORD=password
  #    - TZ=Europe/Paris
  #    - PGTZ=Europe/Paris
  ## Additionally, you may want to persist data
  ## volumes:
  ##   - /var/lib/buistore/pgsql/10/data:/var/lib/postgresql/data

  burp-server:
    restart: always
    image: registry.ziirish.me/ziirish/burp-ui/burp:2.2.18
    ports:
      - 0.0.0.0:4971:4971
      - 0.0.0.0:4972:4972
    volumes:
      - /etc/burp:/etc/burp
      - /var/spool/burp:/var/spool/burp
      - /var/lib/burp:/var/lib/burp
  # Additionally, you can override some default settings
  #  environment:
  #    - BURP_UID=5337
  #    - BURP_GID=5337
  #    - CHOWN_SPOOL=NO
  #    - TIMEZONE=Europe/Paris

  burpui:
    restart: always
    image: registry.ziirish.me/ziirish/burp-ui:latest
    depends_on:
      - burp-server
      - redis
      - pgsql
    ports:
      - 127.0.0.1:5000:8000
    volumes_from:
      - burp-server
  # Additionally, you can override some default settings
  #  environment:
  #    - BURPUI_CONFIG=/etc/burp/burpui.cfg
  #    - BURPUI_MONITOR_CONFIG=/etc/burp/buimonitor.cfg
  #    - BURPUI_MONITOR_LISTEN=127.0.0.1
  #    - BURPUI_VERBOSE=0
  #    - BURPUI_CLIENT_NAME=bui
  #    - BURPUI_UID=5337
  #    - BURPUI_GID=5337
  #    - BURPUI_PLUGINS=none
  #    - BURPUI_WS_WORKERS=2
  #    - BURPUI_RP_SCHEME=https
  #    - BURPUI_BACKEND=parallel
  #    - BURP_CLIENT_CONFIG=/tmp/burp.conf
  #    - BURP_SERVER_CONFIG=/etc/burp/burp-server.conf
  #    - DATABASE_URL=postgresql://burpui:burpui@pgsql/burpuidb
  #    - GUNICORN_WORKERS=2
  #    - GUNICORN_WORKER_CLASS=sync
  #    - REDIS_SERVER=redis:6379
  #    - BURP_SERVER_ADDR=burp-server
  #    - BURP_RESTORE_LISTEN_ADDR=0.0.0.0:5971
  #    - ASYNC_POOL_SIZE=4
  #    - ASYNC_CONCURRENCY=2
  #    - TIMEZONE=Europe/Paris
