site_name: "Shell History"
site_description: "Visualize your usage of Bash/Zsh through a web app thanks to Flask and Highcharts!"
site_url: "https://pawamoy.github.io/shell-history"
repo_url: "https://github.com/pawamoy/shell-history"
repo_name: "pawamoy/shell-history"

nav:
  - Overview: index.md
  - API Reference:
    - app.py: reference/app.md
    - cli.py: reference/cli.md
    - db.py: reference/db.md
    # - shellhistory.sh: reference/shellhistory.md
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Changelog: changelog.md
  - Credits: credits.md

theme:
  name: material

extra_css:
  - css/mkdocstrings.css

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: "¤"

plugins:
  - search
  - mkdocstrings:
      watch:
        - src/shellhistory
